#if defined _zm_const_included
    #endinput
#endif
#define _zm_const_included

/*******************************************************************************
 * Data/Definitions
 ******************************************************************************/

/**
 * Defines the version of Zombies
 */
#define ZM_VERSION 1.0.0

/**
 * String representation of the version of Zombies. This should match the value
 * of the definition.
 */
stock const String: ZM_VERSION_STRING[] = "1.0.0";

/**
 * String representation for the name of Zombies
 */
stock const String: ZM_NAME[] = "Zombies";

/**
 * String representation for the short name of Zombies
 */
stock const String: ZM_NAME_SHORT[] = "ZM";