#if defined _zm_const_included
    #endinput
#endif
#define _zm_const_included

/*******************************************************************************
 * Data/Definitions
 ******************************************************************************/

/**
 * String representation for the name of Zombies
 */
stock const char ZM_NAME[] = "Zombies";

/**
 * String representation for the short name of Zombies
 */
stock const char ZM_NAME_SHORT[] = "ZM";