#if defined _zm_const_included
    #endinput
#endif
#define _zm_const_included

/*******************************************************************************
 * Data/Definitions
 ******************************************************************************/

/**
 * Defines the mod name of Zombies. This value is used in places before the lang
 * is registered.
 */
#define ZM_MOD_NAME ZM_NAME

/**
 * String representation for the name of Zombies
 */
stock const char ZM_NAME[] = "Zombies";

/**
 * String representation for the short name of Zombies
 */
stock const char ZM_NAME_SHORT[] = "ZM";

#define ZM_LOGS_DIR "zombies"